### ISSUE TITLE
Fatal error during luafilesystem installation (Linux Mint 19, luarocks 4.2.4)

### ISSUE THREAD

**Issue by Mirsait** [lunarmodules/luafilesystem#123]
sudo luarocks install luafilesystem
Installing https://luarocks.org/luafilesystem-1.7.0-2.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.2 -c src/lfs.c -o src/lfs.o
src/lfs.c:66:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
Error: Build error: Failed compiling object src/lfs.o

**Comment by heleg** [comment]
Same problem with Ubuntu 19.04 when `luafilesystem` installed as dependency:
```
Installing https://luarocks.org/luafilesystem-1.7.0-2.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.3 -c src/lfs.c -o src/lfs.o
src/lfs.c:66:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
```

**Comment by heleg** [comment]
Installing `liblua5.3-dev` solved the problem.
