### ISSUE TITLE
Documentation site 404 error?

### ISSUE THREAD

**Issue by mystery-z** [lunarmodules/luafilesystem#162]
The documentation site is giving me a 404 error, is this an error with Github Pages? Or did something happen?

Also is this just me or is this happening for everyone?
Screenshot:
![image](https://user-images.githubusercontent.com/53719487/180088256-71e48174-5b9e-439e-a3d6-8b1c2dc18487.png)

**Comment by Tieske** [comment]
updated the link to https://lunarmodules.github.io/luafilesystem/

thx for the nudge
