### ISSUE TITLE
All functions cause script to abort without error

### ISSUE THREAD

**Issue by davisdude** [lunarmodules/luafilesystem#92]
I installed lfs via luarocks 2.4.2. At first, when trying to use lfs (`lua -l lfs`) I had the error

```
C:\Program Files\lua\5.2.4\bin\lua.exe: module 'lfs' not found:
        no field package.preload['lfs']
        no file 'C:\Program Files (x86)\LuaRocks\lua\lfs.lua'
        no file 'C:\Program Files (x86)\LuaRocks\lua\lfs\init.lua'
        no file 'C:\Program Files\lua\5.2.4\bin\lfs.dll'
        no file 'C:\Program Files\lua\5.2.4\bin\loadall.dll'
        no file '.\lfs.dll'
stack traceback:
        [C]: in function '_G.require'
        [C]: in ?
```

After copying the `.dll` to `C:\Program Files\lua\5.2.4\bin\`, I was able to execute the command `lua -l lfs`, but any attempt to use the commands caused Lua to abort. Here's what I mean:

```
C:\Windows\System32>lua -l lfs
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> print( lfs.currentdir() )

C:\Windows\System32>
```

As you can see, the program is aborted without any information. I don't know if this is relevant, but the error level is `-1073741819`.

**Comment by mpeterv** [comment]
When did luarocks first install lfs.dll? What does `luarocks --help` output in `CONFIGURATION` section?

**Comment by davisdude** [comment]
I'm no longer using Windows, so, unfortunately, I am unable to get that information for you.
